Initial customizations
Still need to verify macos/set-defaults.sh

diff --git a/bin/certp b/bin/certp
--- a/bin/certp
+++ b/bin/certp
@@ -9,7 +9,7 @@
 set -e
 domain="$1"
 test -n "$domain" || {
-	echo "domain missing" >&2
-	exit 1
+    echo "domain missing" >&2
+    exit 1
 }
 echo | openssl s_client -showcerts -servername $domain -connect $domain:443 2>/dev/null | openssl x509 -inform pem -noout -text
